Add runner and sdk methods for Go
konstellation-io/kai-sdk pull request #1
Opened 2023-06-21 08:38 UTC by dfinteligenz

2023-07-07 17:37 UTC, JYisus requested changes
As a general comment, I think it could be helpful fo the users if we expose all the functionality from the same package, so they won't have to know how the internal code is structured and where is all the functionality.

2023-07-07 17:37 UTC, JYisus commented on go-sdk/runner/exit/subscriber.go
>  			os.Exit(1)
This os.Exit(1) could be dangerous, IMO this is not a good practice. I think it could be a better idea to return the error. Also, I don't know if I need more context, but I don't understand why this function is being called as a goroutine. I mean, If u declare a global waitgroup, and then you do: 
```go
go startSubscriber()
wg.Add(1)
wg.Wait()
```

What is happening is that the function behavior is basically synchronous.

In my opinion, it could be clearer for the developers if Run directly returns an error and they decided what to do with it.

2023-07-07 17:37 UTC, JYisus commented on go-sdk/runner/exit/subscriber.go
> +func (er *Runner) processRunnerError(msg *nats.Msg, errMsg, requestID string, start time.Time, fromNode string) {
This function has too many arguments, I think we could avoid those related to metrics, and, when we decide how to store metrics, we can figure out how to handle them.
Maybe we can have all the metrics management in a defer clause in the parent function or something like that.

2023-07-07 17:37 UTC, JYisus commented on go-sdk/runner/runner.go
> +	defer logger.Sync() //nolint: errcheck
I think this should be called in the finalizer, I'm not sure if calling it here has the expected behavior.

2023-07-07 17:37 UTC, JYisus commented on go-sdk/sdk/metadata/metadata.go
> +	return viper.GetString("nats.object-store")
Care with this, it should be _

2023-07-07 17:37 UTC, JYisus commented on go-sdk/sdk/metadata/metadata.go
> +	return viper.GetString("centralized-configuration.product.bucket")
Care with this, it should be _

2023-07-07 17:37 UTC, JYisus commented on go-sdk/sdk/metadata/metadata.go
> +	return viper.GetString("centralized-configuration.workflow.bucket")
Care with this, it should be _

2023-07-07 17:37 UTC, JYisus commented on go-sdk/sdk/metadata/metadata.go
> +	return viper.GetString("centralized-configuration.process.bucket")
Care with this, it should be _

2023-07-07 17:37 UTC, JYisus commented on go-sdk/sdk/object-store/object_store_delete_test.go
> +	natsObjectStoreField = "nats.object-store"
Care with this, it should be _

2023-07-07 17:37 UTC, JYisus commented on demo/rest-trigger/main.go
> +		"object-store", sdk.Metadata.GetObjectStoreName(),
I dont know if this rename is intentional

2023-07-10 11:05 UTC, dfinteligenz commented on go-sdk/runner/exit/subscriber.go
>  			os.Exit(1)
In this case you are correct, the subscriber could be synchronous as there are no more routines running in parallel.

This behaviour was inherited from the trigger process, where there are two routines running, that's why this is running as a go routine.

2023-07-10 11:05 UTC, dfinteligenz commented on go-sdk/runner/exit/subscriber.go
>  			os.Exit(1)
This also applies to the task processes

2023-07-10 11:19 UTC, alexrodfe requested changes
Here is a batch of things I've encountered while I look at the rest

2023-07-10 11:19 UTC, alexrodfe commented on go-sdk/runner/exit/subscriber.go
>  	if responseHandler, ok := er.responseHandlers[subject]; ok {
if we are only allowed to load "default" handler for exit process this check has no place

2023-07-10 11:19 UTC, alexrodfe commented on go-sdk/runner/runner.go
> +	if len(viper.AllKeys()) == 0 {
why equals 0 instead of less than the number of config variables we expect to have?

2023-07-10 11:21 UTC, JYisus commented on go-sdk/runner/exit/subscriber.go
>  			os.Exit(1)
Maybe we can use something like errgroup (https://www.fullstory.com/blog/why-errgroup-withcontext-in-golang-server-handlers/) to handle errors in the trigger process

2023-07-10 13:43 UTC, JYisus approved these changes

2023-07-10 15:25 UTC, alexrodfe commented on go-sdk/runner/exit/exit_runner.go
> +func (er *Runner) WithHandler(handler Handler) *Runner {
Maybe this func could be named "WithDefaultHandler"

2023-07-10 15:33 UTC, alexrodfe approved these changes
Great!
Just one note, anyways I believe this is ready to merge

2023-07-10 21:41 UTC, merged