Fix/knt1 896 aio sdk demo feedback fixes
konstellation-io/kai-sdk pull request #213
Opened 2024-02-07 16:55 UTC by kafkaphoenix

## Description

- Add channel to send error in messaging module
- Make description optional in the method register model 
- Return error in register model if the model already exists
- Move scope from messaging module in go to centralized config
- Return not found error in predictions python update method

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2024-02-07 17:11 UTC, dfinteligenz requested changes

2024-02-07 17:11 UTC, dfinteligenz commented on go-sdk/sdk/centralized-configuration/centralized_configuration_delete_test.go
> +	centralizedconfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
```suggestion
	centralizedConfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
```

Use camelCase for Go.

2024-02-07 17:11 UTC, dfinteligenz commented on go-sdk/sdk/centralized-configuration/centralized_configuration_get_test.go
>  	centralizedconfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
```suggestion
	centralizedConfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
```
Ditto, replace with camelCase

2024-02-07 17:11 UTC, dfinteligenz commented on go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
> +	centralizedconfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
Ditto
```suggestion
	centralizedConfiguration "github.com/konstellation-io/kai-sdk/go-sdk/sdk/centralized-configuration"
```

2024-02-07 17:11 UTC, dfinteligenz commented on go-sdk/sdk/model-registry/model_registry.go
> +
I'd replace this code with a local `modelDescription` variable initialized as an empty string.

And if the `len(description) > 0`, then set `description = description[0]`

2024-02-08 08:19 UTC, kafkaphoenix commented on go-sdk/sdk/centralized-configuration/centralized_configuration.go
> +	_messagingLoggerName       = "[centralizedconfiguration]"
oh right i forgot this one thanks

2024-02-08 08:40 UTC, dfinteligenz approved these changes

2024-02-08 11:14 UTC, merged