Feature/deployments
konstellation-io/kai-sdk pull request #38
Opened 2023-09-27 09:56 UTC by kafkaphoenix

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-09-28 09:36 UTC, alexrodfe approved these changes

2023-09-28 09:57 UTC, alexrodfe approved these changes

2023-10-02 10:43 UTC, JYisus requested changes

2023-10-02 10:43 UTC, JYisus commented on demo/training-workflow/scripts/push_process_registry.sh
> +#!/bin/bash
If this script will be kept in the repo, it should take params to configure de product, server and version

2023-10-02 10:43 UTC, JYisus commented on demo/training-workflow/src/exit/app.yaml
> +metadata:
This config file shouldn't be mandatory, the sdk code should be checked to fix this

2023-10-02 10:43 UTC, JYisus commented on demo/training-workflow/src/exit/config.yaml
> +runner:
same with this file, it should not be mandatory

2023-10-02 10:55 UTC, alexrodfe commented on demo/training-workflow/scripts/push_process_registry.sh
> +#!/bin/bash
I'm not that sure about kli server configuration, we can't do that much for the developer. I believe server should be done and login before hand. We can do it for product but not for version, this is a helping script for developers, if we were to take each image's version as a prompt, the command line would be too difficult and the script not that useful as in having it changed in your local.

2023-10-02 10:56 UTC, alexrodfe commented on demo/training-workflow/scripts/push_process_registry.sh
> +#!/bin/bash
I coded it for myself, thought it could prove useful for other developers. We can add it to the gitignore file anyways.

2023-10-02 11:16 UTC, kafkaphoenix commented on demo/training-workflow/scripts/push_process_registry.sh
> +#!/bin/bash
good idea

2023-10-03 15:24 UTC, kafkaphoenix commented on demo/training-workflow/src/exit/app.yaml
> +metadata:
they are not mandatory as we have seen later just in local, the files will be removed for this workflow in another pr

2023-10-03 15:25 UTC, kafkaphoenix commented on demo/training-workflow/src/exit/config.yaml
> +runner:
they are not mandatory as we have seen later just in local, the files will be removed for this workflow in another pr

2023-10-03 15:30 UTC, merged