Feature/add request id to logging
konstellation-io/kai-sdk pull request #57
Opened 2023-10-16 18:02 UTC by dfinteligenz

## Description

- Add Request ID to all logs in the Go SDK
- Update demo Go processes

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-16 18:43 UTC, JYisus requested changes

2023-10-16 18:43 UTC, JYisus commented on demo/exit/go.mod
> +replace github.com/konstellation-io/kai-sdk/go-sdk => ../../go-sdk
Don't forget to delete this before merge

2023-10-16 18:43 UTC, JYisus commented on demo/cronjob-trigger/main.go
> +		sdk.Logger.Info("Cronjob triggered, new message sent", kaiconstants.LoggerRequestID, requestID)
IMO we should not expose these constants to sdk users, they may be helpful for sdk devs, but users  should be responsible of what they log. Maybe the internal package is a good place for them.

2023-10-17 15:33 UTC, dfinteligenz commented on demo/exit/go.mod
> +replace github.com/konstellation-io/kai-sdk/go-sdk => ../../go-sdk
This is for testing the SDK change in the local environment without having to setup a full KAI locally, and they will be removed in the near future, so I'd let them as they are.

2023-10-17 15:35 UTC, dfinteligenz commented on demo/cronjob-trigger/main.go
> +		sdk.Logger.Info("Cronjob triggered, new message sent", kaiconstants.LoggerRequestID, requestID)
We need to expose them for trigger processes where the requestID has not been set in the logger context yet, we can think of another way of doing it, but the requestID is a must to have full execution tracking

2023-10-17 15:35 UTC, dfinteligenz commented on go-sdk/sdk/kaiconstants/kai_constants.go
> +package kaiconstants
Agreed, we could move them to the KAI package.

2023-10-18 07:01 UTC, kafkaphoenix submitted a review, later dismissed

2023-10-18 09:25 UTC, alexrodfe submitted a review, later dismissed

2023-10-18 11:32 UTC, kafkaphoenix submitted a review, later dismissed

2023-10-18 15:24 UTC, alexrodfe submitted a review, later dismissed

2023-10-19 09:14 UTC, alexrodfe approved these changes

2023-10-19 10:02 UTC, kafkaphoenix approved these changes

2023-10-20 10:29 UTC, alexrodfe submitted a review, later dismissed

2023-10-20 11:25 UTC, kafkaphoenix submitted a review, later dismissed

2023-10-20 12:18 UTC, kafkaphoenix approved these changes

2023-10-20 12:46 UTC, kafkaphoenix approved these changes

2023-10-20 12:49 UTC, merged