feat(go-sdk): new method unmarshall message
konstellation-io/kai-sdk pull request #70
Opened 2023-10-23 12:01 UTC by kafkaphoenix

## Description

As users sometimes we need to unmarshall messages like in the process trigger use case so we can get back the request ID

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-24 11:34 UTC, alexrodfe commented on go-sdk/sdk/messaging/messaging_internals.go
> +func (ms Messaging) GetRequestID(data []byte) (string, error) {
Perhaps a "GetRequestIDFromAny" would be more suitable, it is rather a larger method name, but just to add context

2023-10-24 11:35 UTC, alexrodfe approved these changes

2023-10-24 14:00 UTC, kafkaphoenix commented on go-sdk/sdk/messaging/messaging_internals.go
> +func (ms Messaging) GetRequestID(data []byte) (string, error) {
i thought about it but data already suggests the origin of the request id

2023-10-25 17:50 UTC, dfinteligenz requested changes

2023-10-25 17:50 UTC, dfinteligenz commented on go-sdk/sdk/messaging/messaging_internals.go
> +func (ms Messaging) GetRequestID(data []byte) (string, error) {
Why don't we receive a `nats.Msg` as an input parameter?
That way it's clearer that this method is for extracting the RequestID from a `nats.Msg`, not from any byte array.

2023-10-25 17:50 UTC, dfinteligenz commented on py-sdk/sdk/sdk/messaging/messaging.py
> +    def get_request_id(self, data: bytes) -> (str, Exception):
ditto

2023-10-26 09:43 UTC, kafkaphoenix commented on go-sdk/sdk/messaging/messaging_internals.go
> +func (ms Messaging) GetRequestID(data []byte) (string, error) {
updated

2023-10-26 09:43 UTC, kafkaphoenix commented on py-sdk/sdk/sdk/messaging/messaging.py
> +    def get_request_id(self, data: bytes) -> (str, Exception):
done

2023-10-26 09:58 UTC, alexrodfe approved these changes

2023-10-26 10:31 UTC, dfinteligenz submitted a review, later dismissed

2023-10-26 10:55 UTC, dfinteligenz approved these changes

2023-10-26 12:05 UTC, merged