Feature/add persistant storage methods
konstellation-io/kai-sdk pull request #73
Opened 2023-10-26 12:12 UTC by kafkaphoenix

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-30 07:56 UTC, dfinteligenz commented on demo/cronjob-trigger-py/app.yaml
> +
Just a couple of changes @kafkaphoenix.

We will finally be using the next configuration (some naming changes, and remove the region):
```yaml
minio:
  url: "localhost:9000"
  access_key_id: minioadmin
  access_key_secret: minioadmin
  use_ssl: false
  bucket: test-bucket
````

2023-10-30 07:57 UTC, dfinteligenz requested changes
We need to do a small change, check the comment above.

2023-10-30 08:15 UTC, kafkaphoenix commented on demo/cronjob-trigger-py/app.yaml
> +
going to update and all of them and the validators

2023-10-30 08:32 UTC, kafkaphoenix commented on demo/cronjob-trigger-py/app.yaml
> +
done

2023-10-31 12:14 UTC, dfinteligenz approved these changes

2023-10-31 12:22 UTC, merged