Add persistent storage methods to the Go SDK
konstellation-io/kai-sdk pull request #81
Opened 2023-10-30 07:52 UTC by dfinteligenz

## Description
- Add persistent storage methods to the Go SDK
- Add examples of the persistent storage usage to the Demo processes
- Fix some minor log labels issues

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [x] I have executed the pre-commit hooks locally.
- [x] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-30 08:42 UTC, kafkaphoenix commented on go-sdk/sdk/kai_sdk.go
> +	Save(key string, value []byte) (string, error)
aren't you missing ttl parameter here?

2023-10-30 08:46 UTC, kafkaphoenix commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +		-1,
in the python version here i'm doing len of the payload
(Warning: passing -1 will allocate a large amount  of memory)

2023-10-31 16:10 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +		-1,
I'll change it to have the same logic in both python an go, but in theory this wouldn't be relevant to uploads.

2023-11-06 13:58 UTC, JYisus commented on go-sdk/sdk/ephemeral-storage/ephemeral_storage.go
> +		logger:                 logger.WithName("[EPHEMERAL STORAGE]"),
Maybe the logger name could be defined as a constant (like in some other cases), but this could be a future improvement

2023-11-06 14:11 UTC, JYisus requested changes

2023-11-06 14:11 UTC, JYisus commented on go-sdk/sdk/persistent-storage/export_test.go
> +func NewPersistentStorageBuilder(logger logr.Logger, mock persistentStorageInterface) (*PersistentStorage, error) {
This won't return an error, why keep it here?

2023-11-06 14:11 UTC, JYisus commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	endpoint := viper.GetString("minio.endpoint")
IMO, we should define the keys as constants, keeping them as strings is prone to errors and hard to maintain if this config structure changes

2023-11-06 14:11 UTC, JYisus commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Object %s successfully deleted from persistent storage", key)
Is this working as expected? Logr Info is not an Infof

2023-11-06 15:25 UTC, alexrodfe commented on go-sdk/sdk/kai_sdk.go
> +	ListVersions(key string) ([]string, error)
This name could be misleading towards product versions, maybe "ListObjectVersions" could be more clear

2023-11-06 15:33 UTC, alexrodfe commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	if payload == nil {
payload can be of len = 0 even if not nil

2023-11-06 15:34 UTC, alexrodfe commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	if len(ttlDays) > 0 && ttlDays[0] > 0 {
what if retain date is 0?
object will be saved with no retain date

2023-11-06 15:40 UTC, alexrodfe commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Objects successfully retrieved from persistent storage")
Even if result list length is 0, this log shows up, could be misleading

2023-11-06 15:41 UTC, alexrodfe commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Object versions successfully retrieved for prefix %s from persistent storage", key)
ditto above

2023-11-06 15:41 UTC, alexrodfe commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +		if object.Key != "" && object.VersionID != "" {
we are searching with prefix, key should be never empty

2023-11-06 15:46 UTC, alexrodfe reviewed
Great work! I have some questions before proceeding

2023-11-06 15:50 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Object %s successfully deleted from persistent storage", key)
Nop, it adds the label to the log but without any value.
Not what we were looking for.

2023-11-06 15:54 UTC, dfinteligenz commented on go-sdk/sdk/ephemeral-storage/ephemeral_storage.go
> +		logger:                 logger.WithName("[EPHEMERAL STORAGE]"),
We can leave it for a future refactor, for now I'll leave it as is, as in other constructors.

2023-11-06 15:54 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/export_test.go
> +func NewPersistentStorageBuilder(logger logr.Logger, mock persistentStorageInterface) (*PersistentStorage, error) {
This is following the original constructor's contract, but I agree with you that for testing purposes, the error is never going to be used.

2023-11-06 16:22 UTC, dfinteligenz commented on go-sdk/sdk/kai_sdk.go
> +	ListVersions(key string) ([]string, error)
These methods are contained inside the `Storage.Persistent` struct, IMO that should be enough context.

2023-11-06 16:22 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	if payload == nil {
Good catch!

2023-11-06 16:26 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	if len(ttlDays) > 0 && ttlDays[0] > 0 {
0 is not considered a valid value for ttlDays, if the ttlDays is 0 or less, the TTL is not applied.

2023-11-06 16:28 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Objects successfully retrieved from persistent storage")
This behavior is correct, if you list the objects of a bucket and there are none, the log says that all the objects were correctly retrieved.

2023-11-06 16:41 UTC, alexrodfe commented on go-sdk/sdk/kai_sdk.go
> +	ListVersions(key string) ([]string, error)
True that, I agree

2023-11-06 16:41 UTC, alexrodfe approved these changes

2023-11-07 09:30 UTC, merged