Aauthentication persistent storage
konstellation-io/kai-sdk pull request #91
Opened 2023-11-03 15:54 UTC by dfinteligenz

## Description

Add external IdP authentication for the persistent storage.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-06 14:15 UTC, JYisus requested changes

2023-11-06 14:15 UTC, JYisus commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Object %s successfully stored in persistent storage with version ID %s",
I think this is not working as expected

2023-11-06 14:15 UTC, JYisus commented on go-sdk/sdk/persistent-storage/persistent_storage_test.go
> +	minioEndpoint := fmt.Sprintf("%s:%d", host, port.Int())
You can use s.minioContainer.PortEndpoint instead of MappedPort and it should return the whole enpoint

2023-11-07 08:16 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage.go
> +	ps.logger.V(1).Info("Object %s successfully stored in persistent storage with version ID %s",
Fixed in previous PR

2023-11-07 16:28 UTC, dfinteligenz commented on go-sdk/sdk/persistent-storage/persistent_storage_test.go
> +	minioEndpoint := fmt.Sprintf("%s:%d", host, port.Int())
In the way we do it now we don't need to know the protocol to generated the endpoint, as the container Host already returns the correct one.

2023-11-08 09:01 UTC, JYisus submitted a review, later dismissed

2023-11-08 15:18 UTC, alexrodfe approved these changes

2023-11-08 15:18 UTC, merged